In [ ]:
# prompt: load the excel file ive loaded already

import pandas as pd
df = pd.read_excel('mobile_customers.xlsx') # replace filename.xlsx with your filename
df.head(5)

,Unnamed: 0,customer_id,date_registered,username,name,gender,address,email,birthdate,current_location,residence,employer,job,age,salary,credit_card_provider,credit_card_number,credit_card_security_code,credit_card_expire
0,0,24c9d2d0-d0d3-4a90-9a3a-e00e4aac99bd,2021-09-29,robertsbryan,Jonathan Snyder,M,"24675 Susan Valley\nNorth Dianabury, MO 02475",marcus58@hotmail.com,1978-03-11,"['78.937112', '71.260464']","195 Brandi Junctions\nNew Julieberg, NE 63410","Byrd, Welch and Holt",Chief Technology Officer,49,53979,VISA 19 digit,38985874269846,994,2023-10-27 00:00:00
1,1,7b2bc220-0296-4914-ba46-d6cc6a55a62a,2019-08-17,egarcia,Susan Dominguez,F,"4212 Cheryl Inlet\nPort Davidmouth, NC 54884",alexanderkathy@hotmail.com,1970-11-29,"['-24.1692185', '100.746122']","58272 Brown Isle Apt. 698\nPort Michael, HI 04693",Hurst PLC,Data scientist,43,81510,Discover,6525743622515979,163,2023-07-30 00:00:00
2,2,06febdf9-07fb-4a1b-87d7-a5f97d9a5faf,2019-11-01,turnermegan,Corey Hebert,M,"07388 Coleman Prairie\nLake Amy, IA 78695",vwood@gmail.com,2009-04-23,"['8.019908', '-19.603269']","36848 Jones Lane Suite 282\nMarquezbury, ID 26822","Mora, Caldwell and Guerrero",Chief Operating Officer,47,205345,VISA 16 digit,4010729915028682247,634,2023-04-26 00:00:00
3,3,23df88e5-5dd3-46af-ac0d-0c6bd92e4b96,2021-12-31,richardcampbell,Latasha Griffin,F,"PSC 6217, Box 2610\nAPO AA 53585",kathleen36@gmail.com,1992-07-27,"['62.497506', '2.717198']","317 Lamb Cape Apt. 884\nLake Amy, DC 79074",Patel PLC,Counselling psychologist,34,116095,VISA 16 digit,4854862659569207844,7957,2023-10-31 00:00:00
4,4,6069c2d7-7905-4993-a155-64f6aba143b1,2020-08-09,timothyjackson,Colleen Wheeler,F,"0325 Potter Roads\nLake Lisashire, NM 77502",johnbest@hotmail.com,1989-09-16,"['73.7924695', '-80.314720']","21936 Mary Islands\nMendozafort, TN 37124",Smith-Mejia,Mining engineer,57,107529,JCB 16 digit,213152724828217,72,2023-05-28 00:00:00

In [ ]:
df = df.drop(['customer_id', 'current_location'], axis=1)
df.head(5)

,Unnamed: 0,date_registered,username,name,gender,address,email,birthdate,residence,employer,job,age,salary,credit_card_provider,credit_card_number,credit_card_security_code,credit_card_expire
0,0,2021-09-29,robertsbryan,Jonathan Snyder,M,"24675 Susan Valley\nNorth Dianabury, MO 02475",marcus58@hotmail.com,1978-03-11,"195 Brandi Junctions\nNew Julieberg, NE 63410","Byrd, Welch and Holt",Chief Technology Officer,49,53979,VISA 19 digit,38985874269846,994,2023-10-27 00:00:00
1,1,2019-08-17,egarcia,Susan Dominguez,F,"4212 Cheryl Inlet\nPort Davidmouth, NC 54884",alexanderkathy@hotmail.com,1970-11-29,"58272 Brown Isle Apt. 698\nPort Michael, HI 04693",Hurst PLC,Data scientist,43,81510,Discover,6525743622515979,163,2023-07-30 00:00:00
2,2,2019-11-01,turnermegan,Corey Hebert,M,"07388 Coleman Prairie\nLake Amy, IA 78695",vwood@gmail.com,2009-04-23,"36848 Jones Lane Suite 282\nMarquezbury, ID 26822","Mora, Caldwell and Guerrero",Chief Operating Officer,47,205345,VISA 16 digit,4010729915028682247,634,2023-04-26 00:00:00
3,3,2021-12-31,richardcampbell,Latasha Griffin,F,"PSC 6217, Box 2610\nAPO AA 53585",kathleen36@gmail.com,1992-07-27,"317 Lamb Cape Apt. 884\nLake Amy, DC 79074",Patel PLC,Counselling psychologist,34,116095,VISA 16 digit,4854862659569207844,7957,2023-10-31 00:00:00
4,4,2020-08-09,timothyjackson,Colleen Wheeler,F,"0325 Potter Roads\nLake Lisashire, NM 77502",johnbest@hotmail.com,1989-09-16,"21936 Mary Islands\nMendozafort, TN 37124",Smith-Mejia,Mining engineer,57,107529,JCB 16 digit,213152724828217,72,2023-05-28 00:00:00

In [ ]:
df['username'] = df['username'].apply(lambda x: x[0] + '*'*(len(x)-2) + x[-1])
df.head(5)

,Unnamed: 0,date_registered,username,name,gender,address,email,birthdate,residence,employer,job,age,salary,credit_card_provider,credit_card_number,credit_card_security_code,credit_card_expire
0,0,2021-09-29,r**********n,Jonathan Snyder,M,"24675 Susan Valley\nNorth Dianabury, MO 02475",marcus58@hotmail.com,1978-03-11,"195 Brandi Junctions\nNew Julieberg, NE 63410","Byrd, Welch and Holt",Chief Technology Officer,49,53979,VISA 19 digit,38985874269846,994,2023-10-27 00:00:00
1,1,2019-08-17,e*****a,Susan Dominguez,F,"4212 Cheryl Inlet\nPort Davidmouth, NC 54884",alexanderkathy@hotmail.com,1970-11-29,"58272 Brown Isle Apt. 698\nPort Michael, HI 04693",Hurst PLC,Data scientist,43,81510,Discover,6525743622515979,163,2023-07-30 00:00:00
2,2,2019-11-01,t*********n,Corey Hebert,M,"07388 Coleman Prairie\nLake Amy, IA 78695",vwood@gmail.com,2009-04-23,"36848 Jones Lane Suite 282\nMarquezbury, ID 26822","Mora, Caldwell and Guerrero",Chief Operating Officer,47,205345,VISA 16 digit,4010729915028682247,634,2023-04-26 00:00:00
3,3,2021-12-31,r*************l,Latasha Griffin,F,"PSC 6217, Box 2610\nAPO AA 53585",kathleen36@gmail.com,1992-07-27,"317 Lamb Cape Apt. 884\nLake Amy, DC 79074",Patel PLC,Counselling psychologist,34,116095,VISA 16 digit,4854862659569207844,7957,2023-10-31 00:00:00
4,4,2020-08-09,t************n,Colleen Wheeler,F,"0325 Potter Roads\nLake Lisashire, NM 77502",johnbest@hotmail.com,1989-09-16,"21936 Mary Islands\nMendozafort, TN 37124",Smith-Mejia,Mining engineer,57,107529,JCB 16 digit,213152724828217,72,2023-05-28 00:00:00

In [ ]:
df_copy = df.copy()

In [ ]:
df.head(5)

,Unnamed: 0,date_registered,username,name,gender,address,email,birthdate,residence,employer,job,age,salary,credit_card_provider,credit_card_number,credit_card_security_code,credit_card_expire
0,0,2021-09-29,r**********n,Jonathan Snyder,M,"24675 Susan Valley\nNorth Dianabury, MO 02475",marcus58@hotmail.com,1978-03-11,"195 Brandi Junctions\nNew Julieberg, NE 63410","Byrd, Welch and Holt",Chief Technology Officer,49,53979,VISA 19 digit,38985874269846,994,2023-10-27 00:00:00
1,1,2019-08-17,e*****a,Susan Dominguez,F,"4212 Cheryl Inlet\nPort Davidmouth, NC 54884",alexanderkathy@hotmail.com,1970-11-29,"58272 Brown Isle Apt. 698\nPort Michael, HI 04693",Hurst PLC,Data scientist,43,81510,Discover,6525743622515979,163,2023-07-30 00:00:00
2,2,2019-11-01,t*********n,Corey Hebert,M,"07388 Coleman Prairie\nLake Amy, IA 78695",vwood@gmail.com,2009-04-23,"36848 Jones Lane Suite 282\nMarquezbury, ID 26822","Mora, Caldwell and Guerrero",Chief Operating Officer,47,205345,VISA 16 digit,4010729915028682247,634,2023-04-26 00:00:00
3,3,2021-12-31,r*************l,Latasha Griffin,F,"PSC 6217, Box 2610\nAPO AA 53585",kathleen36@gmail.com,1992-07-27,"317 Lamb Cape Apt. 884\nLake Amy, DC 79074",Patel PLC,Counselling psychologist,34,116095,VISA 16 digit,4854862659569207844,7957,2023-10-31 00:00:00
4,4,2020-08-09,t************n,Colleen Wheeler,F,"0325 Potter Roads\nLake Lisashire, NM 77502",johnbest@hotmail.com,1989-09-16,"21936 Mary Islands\nMendozafort, TN 37124",Smith-Mejia,Mining engineer,57,107529,JCB 16 digit,213152724828217,72,2023-05-28 00:00:00

In [ ]:
import names

# Generate a list of fake names equal to the number of rows in the DataFrame
fake_names = [names.get_full_name() for _ in range(len(df))]

# Replace the 'name' column with the list of fake names
df['name'] = fake_names

print(df)

      Unnamed: 0 date_registered         username             name gender  \
0              0      2021-09-29     r**********n   Daniel Scianna      M
1              1      2019-08-17          e*****a      Michael Fry      F
2              2      2019-11-01      t*********n        Alan Blum      M
3              3      2021-12-31  r*************l     Mellie White      F
4              4      2020-08-09   t************n  Kristie Patrick      F
...          ...             ...              ...              ...    ...
9995        9995      2021-09-12    w***********k   Kimberely Tate      F
9996        9996      2020-08-15        b*******z      Donna Young      F
9997        9997      2019-10-24          j*****s      Jean Fisher      F
9998        9998      2020-08-14      j*********s   Matilde Thomas      M
9999        9999      2020-04-04     b**********w      Elmer Henry      M

                                                address  \
0         24675 Susan Valley\nNorth Dianabury, MO 02475
1          4212 Cheryl Inlet\nPort Davidmouth, NC 54884
2             07388 Coleman Prairie\nLake Amy, IA 78695
3                      PSC 6217, Box 2610\nAPO AA 53585
4           0325 Potter Roads\nLake Lisashire, NM 77502
...                                                 ...
9995                   Unit 5088 Box 8191\nDPO AA 18373
9996  38388 Joseph Drive Apt. 442\nPort Thomas, NH 1...
9997             4880 Newman Square\nColeberg, AK 41248
9998           68770 Wright Plaza\nStevemouth, NM 11812
9999                   PSC 6109, Box 8247\nAPO AA 57422

                           email  birthdate  \
0           marcus58@hotmail.com 1978-03-11
1     alexanderkathy@hotmail.com 1970-11-29
2                vwood@gmail.com 2009-04-23
3           kathleen36@gmail.com 1992-07-27
4           johnbest@hotmail.com 1989-09-16
...                          ...        ...
9995           jlawson@yahoo.com 1975-07-13
9996    rebeccaramirez@gmail.com 1940-10-19
9997       brownsandra@gmail.com 1994-12-27
9998             wreed@gmail.com 1961-03-07
9999           nfields@yahoo.com 2015-10-27

                                              residence  \
0         195 Brandi Junctions\nNew Julieberg, NE 63410
1     58272 Brown Isle Apt. 698\nPort Michael, HI 04693
2     36848 Jones Lane Suite 282\nMarquezbury, ID 26822
3            317 Lamb Cape Apt. 884\nLake Amy, DC 79074
4             21936 Mary Islands\nMendozafort, TN 37124
...                                                 ...
9995  53290 Jessica Pike Suite 808\nNorth Patricia, ...
9996  21271 Anthony Ports Apt. 438\nButlerport, ND 7...
9997     7949 Simmons Cape\nNew Glendaborough, NJ 90980
9998       3421 Katherine Wall\nEast Markside, NE 95730
9999                   Unit 7808 Box 8797\nDPO AA 44228

                         employer                       job  age  salary  \
0            Byrd, Welch and Holt  Chief Technology Officer   49   53979
1                       Hurst PLC            Data scientist   43   81510
2     Mora, Caldwell and Guerrero   Chief Operating Officer   47  205345
3                       Patel PLC  Counselling psychologist   34  116095
4                     Smith-Mejia           Mining engineer   57  107529
...                           ...                       ...  ...     ...
9995                   Palmer Inc        Press photographer   57  241058
9996   Adams, Mckee and Maldonado            Phytotherapist   33   26398
9997              Fernandez Group      Chartered accountant   24  244563
9998   Warner, Munoz and Franklin             Oceanographer   44  232825
9999                    Payne Ltd              Town planner   48  168859

             credit_card_provider   credit_card_number  \
0                   VISA 19 digit       38985874269846
1                        Discover     6525743622515979
2                   VISA 16 digit  4010729915028682247
3                   VISA 16 digit  4854862659569207844
4                    JCB 16 digit      213152724828217
...                           ...                  ...
9995  Diners Club / Carte Blanche     4522452929113284
9996                VISA 13 digit     4647267952761431
9997                     Discover     2286190388812018
9998             American Express     3582143232994788
9999                   Mastercard      180039538272220

      credit_card_security_code   credit_card_expire
0                           994  2023-10-27 00:00:00
1                           163  2023-07-30 00:00:00
2                           634  2023-04-26 00:00:00
3                          7957  2023-10-31 00:00:00
4                            72  2023-05-28 00:00:00
...                         ...                  ...
9995                        448  2023-06-27 00:00:00
9996                        227  2023-12-31 00:00:00
9997                        877  2023-06-24 00:00:00
9998                         92  2023-04-28 00:00:00
9999                        445  2023-12-30 00:00:00

[10000 rows x 17 columns]

In [ ]:
df.head(5)

,Unnamed: 0,date_registered,username,name,gender,address,email,birthdate,residence,employer,job,age,salary,credit_card_provider,credit_card_number,credit_card_security_code,credit_card_expire
0,0,2021-09-29,r**********n,Daniel Scianna,M,"24675 Susan Valley\nNorth Dianabury, MO 02475",marcus58@hotmail.com,1978-03-11,"195 Brandi Junctions\nNew Julieberg, NE 63410","Byrd, Welch and Holt",Chief Technology Officer,49,53979,VISA 19 digit,38985874269846,994,2023-10-27 00:00:00
1,1,2019-08-17,e*****a,Michael Fry,F,"4212 Cheryl Inlet\nPort Davidmouth, NC 54884",alexanderkathy@hotmail.com,1970-11-29,"58272 Brown Isle Apt. 698\nPort Michael, HI 04693",Hurst PLC,Data scientist,43,81510,Discover,6525743622515979,163,2023-07-30 00:00:00
2,2,2019-11-01,t*********n,Alan Blum,M,"07388 Coleman Prairie\nLake Amy, IA 78695",vwood@gmail.com,2009-04-23,"36848 Jones Lane Suite 282\nMarquezbury, ID 26822","Mora, Caldwell and Guerrero",Chief Operating Officer,47,205345,VISA 16 digit,4010729915028682247,634,2023-04-26 00:00:00
3,3,2021-12-31,r*************l,Mellie White,F,"PSC 6217, Box 2610\nAPO AA 53585",kathleen36@gmail.com,1992-07-27,"317 Lamb Cape Apt. 884\nLake Amy, DC 79074",Patel PLC,Counselling psychologist,34,116095,VISA 16 digit,4854862659569207844,7957,2023-10-31 00:00:00
4,4,2020-08-09,t************n,Kristie Patrick,F,"0325 Potter Roads\nLake Lisashire, NM 77502",johnbest@hotmail.com,1989-09-16,"21936 Mary Islands\nMendozafort, TN 37124",Smith-Mejia,Mining engineer,57,107529,JCB 16 digit,213152724828217,72,2023-05-28 00:00:00

In [ ]:
def mask_email(email):
  parts = email.split('@')
  username = parts[0]
  domain = parts[1]
  masked_username = username[0] + '*'*(len(username)-2) + username[-1]
  return masked_username + '@' + domain

df['email'] = df['email'].apply(mask_email)
df.head(5)

,Unnamed: 0,date_registered,username,name,gender,address,email,birthdate,residence,employer,job,age,salary,credit_card_provider,credit_card_number,credit_card_security_code,credit_card_expire
0,0,2021-09-29,r**********n,Daniel Scianna,M,"24675 Susan Valley\nNorth Dianabury, MO 02475",m******8@hotmail.com,1978-03-11,"195 Brandi Junctions\nNew Julieberg, NE 63410","Byrd, Welch and Holt",Chief Technology Officer,49,53979,VISA 19 digit,38985874269846,994,2023-10-27 00:00:00
1,1,2019-08-17,e*****a,Michael Fry,F,"4212 Cheryl Inlet\nPort Davidmouth, NC 54884",a************y@hotmail.com,1970-11-29,"58272 Brown Isle Apt. 698\nPort Michael, HI 04693",Hurst PLC,Data scientist,43,81510,Discover,6525743622515979,163,2023-07-30 00:00:00
2,2,2019-11-01,t*********n,Alan Blum,M,"07388 Coleman Prairie\nLake Amy, IA 78695",v***d@gmail.com,2009-04-23,"36848 Jones Lane Suite 282\nMarquezbury, ID 26822","Mora, Caldwell and Guerrero",Chief Operating Officer,47,205345,VISA 16 digit,4010729915028682247,634,2023-04-26 00:00:00
3,3,2021-12-31,r*************l,Mellie White,F,"PSC 6217, Box 2610\nAPO AA 53585",k********6@gmail.com,1992-07-27,"317 Lamb Cape Apt. 884\nLake Amy, DC 79074",Patel PLC,Counselling psychologist,34,116095,VISA 16 digit,4854862659569207844,7957,2023-10-31 00:00:00
4,4,2020-08-09,t************n,Kristie Patrick,F,"0325 Potter Roads\nLake Lisashire, NM 77502",j******t@hotmail.com,1989-09-16,"21936 Mary Islands\nMendozafort, TN 37124",Smith-Mejia,Mining engineer,57,107529,JCB 16 digit,213152724828217,72,2023-05-28 00:00:00

In [ ]:
import random
from datetime import timedelta

def add_noise_to_date(date):
  days_noise = random.randint(-30, 30)  # Adjust the range as needed
  noisy_date = date + timedelta(days=days_noise)
  return noisy_date

df['date_registered'] = pd.to_datetime(df['date_registered']).apply(add_noise_to_date)
df['birthdate'] = pd.to_datetime(df['birthdate']).apply(add_noise_to_date)

df.head(5)

,Unnamed: 0,date_registered,username,name,gender,address,email,birthdate,residence,employer,job,age,salary,credit_card_provider,credit_card_number,credit_card_security_code,credit_card_expire
0,0,2021-10-13,r**********n,Daniel Scianna,M,"24675 Susan Valley\nNorth Dianabury, MO 02475",m******8@hotmail.com,1978-02-21,"195 Brandi Junctions\nNew Julieberg, NE 63410","Byrd, Welch and Holt",Chief Technology Officer,49,53979,VISA 19 digit,38985874269846,994,2023-10-27 00:00:00
1,1,2019-08-04,e*****a,Michael Fry,F,"4212 Cheryl Inlet\nPort Davidmouth, NC 54884",a************y@hotmail.com,1970-12-08,"58272 Brown Isle Apt. 698\nPort Michael, HI 04693",Hurst PLC,Data scientist,43,81510,Discover,6525743622515979,163,2023-07-30 00:00:00
2,2,2019-11-03,t*********n,Alan Blum,M,"07388 Coleman Prairie\nLake Amy, IA 78695",v***d@gmail.com,2009-03-24,"36848 Jones Lane Suite 282\nMarquezbury, ID 26822","Mora, Caldwell and Guerrero",Chief Operating Officer,47,205345,VISA 16 digit,4010729915028682247,634,2023-04-26 00:00:00
3,3,2022-01-05,r*************l,Mellie White,F,"PSC 6217, Box 2610\nAPO AA 53585",k********6@gmail.com,1992-07-23,"317 Lamb Cape Apt. 884\nLake Amy, DC 79074",Patel PLC,Counselling psychologist,34,116095,VISA 16 digit,4854862659569207844,7957,2023-10-31 00:00:00
4,4,2020-09-04,t************n,Kristie Patrick,F,"0325 Potter Roads\nLake Lisashire, NM 77502",j******t@hotmail.com,1989-10-14,"21936 Mary Islands\nMendozafort, TN 37124",Smith-Mejia,Mining engineer,57,107529,JCB 16 digit,213152724828217,72,2023-05-28 00:00:00

In [ ]:
# Define bins and labels for salary
salary_bins = [0, 25000, 50000, 75000, 100000, float('inf')]
salary_labels = ['<25k', '25k-50k', '50k-75k', '75k-100k', '100k+']

# Define bins and labels for age
age_bins = [0, 18, 25, 35, 50, 65, float('inf')]
age_labels = ['<18', '18-25', '25-35', '35-50', '50-65', '65+']

# Categorize the columns
df['salary_category'] = pd.cut(df['salary'], bins=salary_bins, labels=salary_labels)
df['age_category'] = pd.cut(df['age'], bins=age_bins, labels=age_labels)

# Remove the original salary and age columns
df = df.drop(['salary', 'age'], axis=1)

df.head(5)

,Unnamed: 0,date_registered,username,name,gender,address,email,birthdate,residence,employer,job,credit_card_provider,credit_card_number,credit_card_security_code,credit_card_expire,salary_category,age_category
0,0,2021-10-13,r**********n,Daniel Scianna,M,"24675 Susan Valley\nNorth Dianabury, MO 02475",m******8@hotmail.com,1978-02-21,"195 Brandi Junctions\nNew Julieberg, NE 63410","Byrd, Welch and Holt",Chief Technology Officer,VISA 19 digit,38985874269846,994,2023-10-27 00:00:00,50k-75k,35-50
1,1,2019-08-04,e*****a,Michael Fry,F,"4212 Cheryl Inlet\nPort Davidmouth, NC 54884",a************y@hotmail.com,1970-12-08,"58272 Brown Isle Apt. 698\nPort Michael, HI 04693",Hurst PLC,Data scientist,Discover,6525743622515979,163,2023-07-30 00:00:00,75k-100k,35-50
2,2,2019-11-03,t*********n,Alan Blum,M,"07388 Coleman Prairie\nLake Amy, IA 78695",v***d@gmail.com,2009-03-24,"36848 Jones Lane Suite 282\nMarquezbury, ID 26822","Mora, Caldwell and Guerrero",Chief Operating Officer,VISA 16 digit,4010729915028682247,634,2023-04-26 00:00:00,100k+,35-50
3,3,2022-01-05,r*************l,Mellie White,F,"PSC 6217, Box 2610\nAPO AA 53585",k********6@gmail.com,1992-07-23,"317 Lamb Cape Apt. 884\nLake Amy, DC 79074",Patel PLC,Counselling psychologist,VISA 16 digit,4854862659569207844,7957,2023-10-31 00:00:00,100k+,25-35
4,4,2020-09-04,t************n,Kristie Patrick,F,"0325 Potter Roads\nLake Lisashire, NM 77502",j******t@hotmail.com,1989-10-14,"21936 Mary Islands\nMendozafort, TN 37124",Smith-Mejia,Mining engineer,JCB 16 digit,213152724828217,72,2023-05-28 00:00:00,100k+,50-65

In [ ]:
import uuid

def tokenize_column(column):
  unique_values = column.unique()
  token_map = {value: str(uuid.uuid4())[:10] for value in unique_values}
  return column.map(token_map)

df['credit_card_provider'] = tokenize_column(df['credit_card_provider'])
df['credit_card_expire'] = tokenize_column(df['credit_card_expire'])

print(df[['credit_card_provider', 'credit_card_expire']])

     credit_card_provider credit_card_expire
0              e115fc91-0         d522d08f-8
1              ab691db9-4         00f0cc51-6
2              929c31eb-1         24180658-c
3              929c31eb-1         e40c0ef0-b
4              aa37ba53-e         c7f96e49-d
...                   ...                ...
9995           173dd658-b         3b78b0b4-3
9996           a8b5afd4-4         a393e7e6-c
9997           ab691db9-4         2758ef68-7
9998           cd6286f4-1         f3630108-d
9999           236a1308-8         c38ea84b-5

[10000 rows x 2 columns]

In [ ]:
df.head(5)

,Unnamed: 0,date_registered,username,name,gender,address,email,birthdate,residence,employer,job,credit_card_provider,credit_card_number,credit_card_security_code,credit_card_expire,salary_category,age_category
0,0,2021-10-13,r**********n,Daniel Scianna,M,"24675 Susan Valley\nNorth Dianabury, MO 02475",m******8@hotmail.com,1978-02-21,"195 Brandi Junctions\nNew Julieberg, NE 63410","Byrd, Welch and Holt",Chief Technology Officer,e115fc91-0,38985874269846,994,d522d08f-8,50k-75k,35-50
1,1,2019-08-04,e*****a,Michael Fry,F,"4212 Cheryl Inlet\nPort Davidmouth, NC 54884",a************y@hotmail.com,1970-12-08,"58272 Brown Isle Apt. 698\nPort Michael, HI 04693",Hurst PLC,Data scientist,ab691db9-4,6525743622515979,163,00f0cc51-6,75k-100k,35-50
2,2,2019-11-03,t*********n,Alan Blum,M,"07388 Coleman Prairie\nLake Amy, IA 78695",v***d@gmail.com,2009-03-24,"36848 Jones Lane Suite 282\nMarquezbury, ID 26822","Mora, Caldwell and Guerrero",Chief Operating Officer,929c31eb-1,4010729915028682247,634,24180658-c,100k+,35-50
3,3,2022-01-05,r*************l,Mellie White,F,"PSC 6217, Box 2610\nAPO AA 53585",k********6@gmail.com,1992-07-23,"317 Lamb Cape Apt. 884\nLake Amy, DC 79074",Patel PLC,Counselling psychologist,929c31eb-1,4854862659569207844,7957,e40c0ef0-b,100k+,25-35
4,4,2020-09-04,t************n,Kristie Patrick,F,"0325 Potter Roads\nLake Lisashire, NM 77502",j******t@hotmail.com,1989-10-14,"21936 Mary Islands\nMendozafort, TN 37124",Smith-Mejia,Mining engineer,aa37ba53-e,213152724828217,72,c7f96e49-d,100k+,50-65

In [ ]:
import uuid

def tokenize_column(column):
  unique_values = column.unique()
  token_map = {value: str(uuid.uuid4())[:10] for value in unique_values}
  return column.map(token_map)

df['employer'] = tokenize_column(df['employer'])
df['job'] = tokenize_column(df['job'])

df.head(5)

,Unnamed: 0,date_registered,username,name,gender,address,email,birthdate,residence,employer,job,credit_card_provider,credit_card_number,credit_card_security_code,credit_card_expire,salary_category,age_category
0,0,2021-10-13,r**********n,Daniel Scianna,M,"24675 Susan Valley\nNorth Dianabury, MO 02475",m******8@hotmail.com,1978-02-21,"195 Brandi Junctions\nNew Julieberg, NE 63410",8c7df5ed-d,0a8c7e39-0,e115fc91-0,38985874269846,994,d522d08f-8,50k-75k,35-50
1,1,2019-08-04,e*****a,Michael Fry,F,"4212 Cheryl Inlet\nPort Davidmouth, NC 54884",a************y@hotmail.com,1970-12-08,"58272 Brown Isle Apt. 698\nPort Michael, HI 04693",1bbd5fbd-2,32cd9021-4,ab691db9-4,6525743622515979,163,00f0cc51-6,75k-100k,35-50
2,2,2019-11-03,t*********n,Alan Blum,M,"07388 Coleman Prairie\nLake Amy, IA 78695",v***d@gmail.com,2009-03-24,"36848 Jones Lane Suite 282\nMarquezbury, ID 26822",a2923358-1,81367b25-5,929c31eb-1,4010729915028682247,634,24180658-c,100k+,35-50
3,3,2022-01-05,r*************l,Mellie White,F,"PSC 6217, Box 2610\nAPO AA 53585",k********6@gmail.com,1992-07-23,"317 Lamb Cape Apt. 884\nLake Amy, DC 79074",edc472f0-6,5c2af5f6-8,929c31eb-1,4854862659569207844,7957,e40c0ef0-b,100k+,25-35
4,4,2020-09-04,t************n,Kristie Patrick,F,"0325 Potter Roads\nLake Lisashire, NM 77502",j******t@hotmail.com,1989-10-14,"21936 Mary Islands\nMendozafort, TN 37124",3dbe030f-0,cac4a38f-e,aa37ba53-e,213152724828217,72,c7f96e49-d,100k+,50-65

In [ ]:
!pip install faker==18.11.1

from faker import Faker
fake = Faker()

df['residence'] = df['residence'].apply(lambda x: fake.city())
df['address'] = df['address'].apply(lambda x: fake.address())

df.head(10)

Collecting faker==18.11.1
  Downloading Faker-18.11.1-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: python-dateutil>=2.4 in /usr/local/lib/python3.10/dist-packages (from faker==18.11.1) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.4->faker==18.11.1) (1.16.0)
Downloading Faker-18.11.1-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 18.1 MB/s eta 0:00:00
Installing collected packages: faker
Successfully installed faker-18.11.1

,Unnamed: 0,date_registered,username,name,gender,address,email,birthdate,residence,employer,job,credit_card_provider,credit_card_number,credit_card_security_code,credit_card_expire,salary_category,age_category
0,0,2021-10-13,r**********n,Daniel Scianna,M,"50714 Trevor Lakes Apt. 637\nLake Sharon, FM 6...",m******8@hotmail.com,1978-02-21,Stephaniechester,8c7df5ed-d,0a8c7e39-0,e115fc91-0,38985874269846,994,d522d08f-8,50k-75k,35-50
1,1,2019-08-04,e*****a,Michael Fry,F,"3231 Tammy Gardens Suite 880\nMillerfurt, MO 1...",a************y@hotmail.com,1970-12-08,North Melissa,1bbd5fbd-2,32cd9021-4,ab691db9-4,6525743622515979,163,00f0cc51-6,75k-100k,35-50
2,2,2019-11-03,t*********n,Alan Blum,M,"235 Justin Drives Apt. 142\nNew Kellyhaven, MA...",v***d@gmail.com,2009-03-24,Lake Cameron,a2923358-1,81367b25-5,929c31eb-1,4010729915028682247,634,24180658-c,100k+,35-50
3,3,2022-01-05,r*************l,Mellie White,F,"59730 Crystal Station\nDixonshire, MP 74142",k********6@gmail.com,1992-07-23,Garciafurt,edc472f0-6,5c2af5f6-8,929c31eb-1,4854862659569207844,7957,e40c0ef0-b,100k+,25-35
4,4,2020-09-04,t************n,Kristie Patrick,F,"880 Justin Canyon Suite 271\nGomezfort, MI 08905",j******t@hotmail.com,1989-10-14,New Rachelton,3dbe030f-0,cac4a38f-e,aa37ba53-e,213152724828217,72,c7f96e49-d,100k+,50-65
5,5,2021-12-15,b*********s,Susan Showalter,M,"421 Benitez Track Suite 212\nCarterside, OR 51930",c***********l@hotmail.com,1935-11-15,East Erika,de92dfe3-b,8dadf9ce-1,cd6286f4-1,588418438101,419,a35d4388-d,25k-50k,35-50
6,6,2019-08-17,l**********e,Diana Kramer,F,"PSC 4690, Box 7177\nAPO AE 29141",i*****n@gmail.com,1981-06-09,East Bethanymouth,0e3711ca-7,0f527c9f-b,aa37ba53-e,4155199739994,929,6cc7de05-6,100k+,50-65
7,7,2021-10-22,k***********h,Brad Pepin,F,"904 Baker Plain\nEast Garyland, MO 60026",r**********s@yahoo.com,1923-11-15,Lake Donna,8f3a2dca-a,126f1355-2,173dd658-b,4139784991208906,191,6d2cdbfd-e,50k-75k,50-65
8,8,2021-11-20,s****9,Kimberly Rummler,F,"9690 Chavez Via\nRobertsonville, MO 40041",m**********e@gmail.com,2001-07-01,Sullivanmouth,bb6f1054-7,a44ddede-d,e115fc91-0,4635870474423176,624,f4a3247c-e,100k+,50-65
9,9,2020-03-22,s***********h,Blanca Foy,F,"2800 Roberto Neck\nLake Dan, MH 60337",m*******8@gmail.com,1931-01-14,Moorechester,1a4eb9ec-f,581a6cb2-c,e115fc91-0,4215322906541637,0,c278cf80-b,75k-100k,18-25

In [ ]:
df.head(5)

,Unnamed: 0,date_registered,username,name,gender,address,email,birthdate,residence,employer,job,credit_card_provider,credit_card_number,credit_card_security_code,credit_card_expire,salary_category,age_category
0,0,2021-10-13,r**********n,Daniel Scianna,M,"50714 Trevor Lakes Apt. 637\nLake Sharon, FM 6...",m******8@hotmail.com,1978-02-21,Stephaniechester,8c7df5ed-d,0a8c7e39-0,e115fc91-0,38985874269846,994,d522d08f-8,50k-75k,35-50
1,1,2019-08-04,e*****a,Michael Fry,F,"3231 Tammy Gardens Suite 880\nMillerfurt, MO 1...",a************y@hotmail.com,1970-12-08,North Melissa,1bbd5fbd-2,32cd9021-4,ab691db9-4,6525743622515979,163,00f0cc51-6,75k-100k,35-50
2,2,2019-11-03,t*********n,Alan Blum,M,"235 Justin Drives Apt. 142\nNew Kellyhaven, MA...",v***d@gmail.com,2009-03-24,Lake Cameron,a2923358-1,81367b25-5,929c31eb-1,4010729915028682247,634,24180658-c,100k+,35-50
3,3,2022-01-05,r*************l,Mellie White,F,"59730 Crystal Station\nDixonshire, MP 74142",k********6@gmail.com,1992-07-23,Garciafurt,edc472f0-6,5c2af5f6-8,929c31eb-1,4854862659569207844,7957,e40c0ef0-b,100k+,25-35
4,4,2020-09-04,t************n,Kristie Patrick,F,"880 Justin Canyon Suite 271\nGomezfort, MI 08905",j******t@hotmail.com,1989-10-14,New Rachelton,3dbe030f-0,cac4a38f-e,aa37ba53-e,213152724828217,72,c7f96e49-d,100k+,50-65

In [ ]:
df.columns

Index(['Unnamed: 0', 'date_registered', 'username', 'name', 'gender',
       'address', 'email', 'birthdate', 'residence', 'employer', 'job',
       'credit_card_provider', 'credit_card_number',
       'credit_card_security_code', 'credit_card_expire', 'salary_category',
       'age_category'],
      dtype='object')

In [ ]:
new_order = ['Unnamed: 0','date_registered', 'username', 'name', 'gender', 'address', 'email', 'birthdate',
             'residence', 'employer', 'job','age_category','salary_category','credit_card_provider', 'credit_card_number',
             'credit_card_security_code', 'credit_card_expire']  # Add any remaining columns in the desired order

df = df[new_order]

df.head(5)

,Unnamed: 0,date_registered,username,name,gender,address,email,birthdate,residence,employer,job,age_category,salary_category,credit_card_provider,credit_card_number,credit_card_security_code,credit_card_expire
0,0,2021-10-13,r**********n,Daniel Scianna,M,"50714 Trevor Lakes Apt. 637\nLake Sharon, FM 6...",m******8@hotmail.com,1978-02-21,Stephaniechester,8c7df5ed-d,0a8c7e39-0,35-50,50k-75k,e115fc91-0,38985874269846,994,d522d08f-8
1,1,2019-08-04,e*****a,Michael Fry,F,"3231 Tammy Gardens Suite 880\nMillerfurt, MO 1...",a************y@hotmail.com,1970-12-08,North Melissa,1bbd5fbd-2,32cd9021-4,35-50,75k-100k,ab691db9-4,6525743622515979,163,00f0cc51-6
2,2,2019-11-03,t*********n,Alan Blum,M,"235 Justin Drives Apt. 142\nNew Kellyhaven, MA...",v***d@gmail.com,2009-03-24,Lake Cameron,a2923358-1,81367b25-5,35-50,100k+,929c31eb-1,4010729915028682247,634,24180658-c
3,3,2022-01-05,r*************l,Mellie White,F,"59730 Crystal Station\nDixonshire, MP 74142",k********6@gmail.com,1992-07-23,Garciafurt,edc472f0-6,5c2af5f6-8,25-35,100k+,929c31eb-1,4854862659569207844,7957,e40c0ef0-b
4,4,2020-09-04,t************n,Kristie Patrick,F,"880 Justin Canyon Suite 271\nGomezfort, MI 08905",j******t@hotmail.com,1989-10-14,New Rachelton,3dbe030f-0,cac4a38f-e,50-65,100k+,aa37ba53-e,213152724828217,72,c7f96e49-d

In [ ]:
df.to_excel('anonymized_data.xlsx', index=False)

In [ ]:
print(df)

      Unnamed: 0 date_registered         username             name gender  \
0              0      2021-10-13     r**********n   Daniel Scianna      M
1              1      2019-08-04          e*****a      Michael Fry      F
2              2      2019-11-03      t*********n        Alan Blum      M
3              3      2022-01-05  r*************l     Mellie White      F
4              4      2020-09-04   t************n  Kristie Patrick      F
...          ...             ...              ...              ...    ...
9995        9995      2021-10-07    w***********k   Kimberely Tate      F
9996        9996      2020-08-08        b*******z      Donna Young      F
9997        9997      2019-10-22          j*****s      Jean Fisher      F
9998        9998      2020-08-11      j*********s   Matilde Thomas      M
9999        9999      2020-04-02     b**********w      Elmer Henry      M

                                                address  \
0     50714 Trevor Lakes Apt. 637\nLake Sharon, FM 6...
1     3231 Tammy Gardens Suite 880\nMillerfurt, MO 1...
2     235 Justin Drives Apt. 142\nNew Kellyhaven, MA...
3           59730 Crystal Station\nDixonshire, MP 74142
4      880 Justin Canyon Suite 271\nGomezfort, MI 08905
...                                                 ...
9995    8438 Poole Bypass Apt. 697\nJulieberg, NY 28471
9996             9199 Joseph Locks\nHartmouth, MS 57644
9997  4936 Harris Route Apt. 893\nBrittanyshire, FL ...
9998  73564 Cynthia Locks Apt. 568\nEast Michelle, V...
9999  239 Porter Corner Apt. 168\nHallborough, OH 60972

                           email  birthdate          residence    employer  \
0           m******8@hotmail.com 1978-02-21   Stephaniechester  8c7df5ed-d
1     a************y@hotmail.com 1970-12-08      North Melissa  1bbd5fbd-2
2                v***d@gmail.com 2009-03-24       Lake Cameron  a2923358-1
3           k********6@gmail.com 1992-07-23         Garciafurt  edc472f0-6
4           j******t@hotmail.com 1989-10-14      New Rachelton  3dbe030f-0
...                          ...        ...                ...         ...
9995           j*****n@yahoo.com 1975-07-22          Codymouth  381566de-0
9996    r************z@gmail.com 1940-11-11       West Madison  dac5a12b-f
9997       b*********a@gmail.com 1994-12-16  West Nicholasberg  176d6a5f-8
9998             w***d@gmail.com 1961-03-27  Port Matthewville  baea83dc-a
9999           n*****s@yahoo.com 2015-11-15  West Adriennefurt  71348ae6-e

             job age_category salary_category credit_card_provider  \
0     0a8c7e39-0        35-50         50k-75k           e115fc91-0
1     32cd9021-4        35-50        75k-100k           ab691db9-4
2     81367b25-5        35-50           100k+           929c31eb-1
3     5c2af5f6-8        25-35           100k+           929c31eb-1
4     cac4a38f-e        50-65           100k+           aa37ba53-e
...          ...          ...             ...                  ...
9995  52a62ef6-4        50-65           100k+           173dd658-b
9996  ec6d75f7-8        25-35         25k-50k           a8b5afd4-4
9997  98971489-3        18-25           100k+           ab691db9-4
9998  5b291d2b-3        35-50           100k+           cd6286f4-1
9999  618fd308-5        35-50           100k+           236a1308-8

       credit_card_number  credit_card_security_code credit_card_expire
0          38985874269846                        994         d522d08f-8
1        6525743622515979                        163         00f0cc51-6
2     4010729915028682247                        634         24180658-c
3     4854862659569207844                       7957         e40c0ef0-b
4         213152724828217                         72         c7f96e49-d
...                   ...                        ...                ...
9995     4522452929113284                        448         3b78b0b4-3
9996     4647267952761431                        227         a393e7e6-c
9997     2286190388812018                        877         2758ef68-7
9998     3582143232994788                         92         f3630108-d
9999      180039538272220                        445         c38ea84b-5

[10000 rows x 17 columns]